-- MySQL Script generated by MySQL Workbench
-- Wed Apr  4 22:34:54 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema inventarios
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema inventarios
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inventarios` DEFAULT CHARACTER SET utf8 ;
USE `inventarios` ;

-- -----------------------------------------------------
-- Table `inventarios`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventarios`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(100) NOT NULL,
  `contrasena` VARCHAR(255) NOT NULL,
  `nombre` VARCHAR(255) NULL,
  `descripcion` VARCHAR(255) NULL,
  `administrador` TINYINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventarios`.`inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventarios`.`inventario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_inventario_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_inventario_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `inventarios`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventarios`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventarios`.`categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `descripcion` VARCHAR(255) NULL,
  `inventario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_categoria_inventario1_idx` (`inventario_id` ASC),
  CONSTRAINT `fk_categoria_inventario1`
    FOREIGN KEY (`inventario_id`)
    REFERENCES `inventarios`.`inventario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventarios`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventarios`.`proveedor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventarios`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventarios`.`producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `descripcion` VARCHAR(255) NULL,
  `categoria_id` INT NOT NULL,
  `proveedor_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_producto_categoria_idx` (`categoria_id` ASC),
  INDEX `fk_producto_proveedor1_idx` (`proveedor_id` ASC),
  CONSTRAINT `fk_producto_categoria`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `inventarios`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_proveedor1`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `inventarios`.`proveedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventarios`.`lote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventarios`.`lote` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `costo` FLOAT NULL,
  `precio` FLOAT NULL,
  `existencia` INT NULL,
  `producto_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_lote_producto1_idx` (`producto_id` ASC),
  CONSTRAINT `fk_lote_producto1`
    FOREIGN KEY (`producto_id`)
    REFERENCES `inventarios`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
